import { View, Text } from "react-native";
import React from "react";
import { images } from "../constants";

export const ExperimentData = [
  {
    id: 1,
    title: "Husky",
    description:
      "Husky is a general name for a sled-type of dog used in northern regions, differentiated from other sled-dog types by their fast pulling style.",
    uploadedImage: images.husky,
    avatar: images.avatar,
    username: "HuskyLover",
    likes: 100,
    dislikes: 34,
    comments: 96,
  },
  {
    id: 2,
    title: "Golden Retriever",
    description:
      "The Golden Retriever is a medium-large gun dog that retrieves shot waterfowl, such as ducks and upland game birds, during hunting and shooting parties.",
    uploadedImage: images.goldenretriever,
    avatar: images.avatar1,
    username: "John Doe",
    likes: 82,
    dislikes: 17,
    comments: 69,
  },
  {
    id: 3,
    title: "Pomeranian",
    description:
      "The Pomeranian is a breed of dog of the Spitz type that is named for the Pomerania region in north-west Poland and north-east Germany in Central Europe.",
    uploadedImage: images.pomeranian,
    avatar: images.avatar2,
    username: "Jane Doe",
    likes: 425,
    dislikes: 81,
    comments: 101,
  },
  {
    id: 4,
    title: "Pomeranian",
    description:
      "The Pomeranian is a breed of dog of the Spitz type that is named for the Pomerania region in north-west Poland and north-east Germany in Central Europe.",
    uploadedImage: images.pomeranian,
    avatar: images.avatar2,
    username: "Jane Doe",
    likes: 425,
    dislikes: 81,
    comments: 101,
  },
];

export const ItemDummy = [
  {
    id: 1,
    title: "Dog Food",
    price: 200000,
    image: images.dogfood,
    rating: 4.8,
    soldUnits: 100,
    shop: "Pet Shop",
  },
  {
    id: 2,
    title: "Bowl",
    price: 50000,
    image: images.dogbowl,
    rating: 4.5,
    soldUnits: 852,
    shop: "Pet Shop",
  },
  {
    id: 3,
    title: "Dog Leash",
    price: 70000,
    image: images.dogleash,
    rating: 4.0,
    soldUnits: 219,
    shop: "My Puppy Shop",
  },
  {
    id: 4,
    title: "Toy",
    price: 30000,
    image: images.dogtoy,
    rating: 5.0,
    soldUnits: 11000,
    shop: "Animal Kingdom",
  },
  {
    id: 5,
    title: "Toy",
    price: 30000,
    image: images.dogtoy,
    rating: 5.0,
    soldUnits: 11000,
    shop: "Animal Kingdom",
  },
  {
    id: 6,
    title: "Toy",
    price: 30000,
    image: images.dogtoy,
    rating: 5.0,
    soldUnits: 11000,
    shop: "Animal Kingdom",
  },
  {
    id: 7,
    title: "Toy",
    price: 30000,
    image: images.dogtoy,
    rating: 5.0,
    soldUnits: 11000,
    shop: "Animal Kingdom",
  },
  {
    id: 8,
    title: "Toy",
    price: 30000,
    image: images.dogtoy,
    rating: 5.0,
    soldUnits: 11000,
    shop: "Animal Kingdom",
  },
];

export const PetDummy = [
  {
    id: 1,
    name: "Chicko",
    image: images.adopt1,
    gender: "Male",
    age: "3 years old",
  },
  {
    id: 2,
    name: "Luna",
    image: images.adopt2,
    gender: "Female",
    age: "2 years old",
  },
  {
    id: 3,
    name: "Borak",
    image: images.adopt3,
    gender: "Male",
    age: "4 years old",
  },
  {
    id: 4,
    name: "Bella",
    image: images.adopt4,
    gender: "Female",
    age: "1 year old",
  },
  {
    id: 5,
    name: "Toby",
    image: images.adopt5,
    gender: "Male",
    age: "6 years old",
  },
  {
    id: 6,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 7,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 8,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 9,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 10,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 11,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 12,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 13,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 14,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
  {
    id: 15,
    name: "Jojo",
    image: images.adopt6,
    gender: "Male",
    age: "8 years old",
  },
];

export const ClinicDummy = [
  {
    id: 1,
    name: "Pet Clinic",
    image: images.clinic1,
    distance: "2.1 km",
    rating: 4.5,
    workingHours: "8:00 AM - 5:00 PM",
    telephone: "0123456789",
  },
  {
    id: 2,
    name: "City Veterinary Hospital",
    image: images.clinic2,
    distance: "3.5 km",
    rating: 4.2,
    workingHours: "9:00 AM - 6:00 PM",
    telephone: "0123456789",
  },
  {
    id: 3,
    name: "Happy Paws Vet Clinic",
    image: images.clinic3,
    distance: "1.8 km",
    rating: 4.7,
    workingHours: "7:00 AM - 4:00 PM",
    telephone: "8832193213",
  },
  {
    id: 4,
    name: "Family Pet Hospital",
    image: images.clinic4,
    distance: "4.2 km",
    rating: 4.0,
    workingHours: "10:00 AM - 7:00 PM",
    telephone: "321356789",
  },
  {
    id: 5,
    name: "Green Valley Veterinary Clinic",
    image: images.clinic5,
    distance: "6.5 km",
    rating: 4.9,
    workingHours: "8:00 AM - 5:00 PM",
    telephone: "321356789",
  },
  {
    id: 6,
    name: "Animal Wellness Clinic",
    image: images.clinic6,
    distance: "2.9 km",
    rating: 4.3,
    workingHours: "9:00 AM - 6:00 PM",
    telephone: "321356789",
  },
  {
    id: 7,
    name: "Best Friends Veterinary Clinic",
    image: images.clinic7,
    distance: "5.7 km",
    rating: 4.6,
    workingHours: "7:00 AM - 4:00 PM",
    telephone: "321356789",
  },
  {
    id: 8,
    name: "Pawfect Pet Care",
    image: images.clinic8,
    distance: "3.3 km",
    rating: 4.8,
    workingHours: "10:00 AM - 7:00 PM",
    telephone: "321356789",
  },
];

export const ProductImages = [
  images.dogfood,
  images.pedigree1,
  images.pedigree2,
  images.pedigree3,
  images.pedigree4,
  images.pedigree5,
];

export const PetImages = [
  images.adopt1,
  images.husky1,
  images.husky2,
  images.husky3,
  images.husky4,
];
